hugoblox:
  schema: "2.0"
  identity:
    name: Françoa Taffarel
    type: person
  theme:
    mode: system
    pack: minimal
    colors:
      primary: blue
      secondary: ""
      neutral: ""
    colors_dark:
      primary: ""
    colors_light:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: compact
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
    theme_picker: true
    language_switcher: true
    cta:
      enable: false
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
  security:
    frame_options: deny
  pro:
    hide_attribution: true

# custom CSS for HugoBlox
custom_css:
  - "css/custom.css"
